x-common: &default-settings
  build:
    context: .
  image: p2p-sim-python:latest
  command: sleep infinity
  networks:
    - project-net

services:
  server1:
    <<: *default-settings
    container_name: server1
    volumes:
      - ./server:/home   # mount server code into /home

  server2:
    <<: *default-settings
    container_name: server2
    volumes:
      - ./server:/home

  server3:
    <<: *default-settings
    container_name: server3
    volumes:
      - ./server:/home

  client1:
    <<: *default-settings
    container_name: client1
    volumes:
      - ./client:/home   # mount client code into /home

  client2:
    <<: *default-settings
    container_name: client2
    volumes:
      - ./client:/home

  client3:
    <<: *default-settings
    container_name: client3
    volumes:
      - ./client:/home

networks:
  project-net:
    external: true
